### ISSUE TITLE
Trying to build minimal example at https://tour.dlang.org/tour/en/dub/lubeck

### ISSUE THREAD

**Issue by EmTee70** [kaleidicassociates/lubeck#7]
I installed some packages at last:
sudo apt install libopenblas-dev

But now I am getting this error:
when running dub -v
....

Search for versions of lapack77 (1 package suppliers)

No versions for lapack77 for registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"])
Nothing found for lapack77
Search for versions of mir-blas (1 package suppliers)
Return for mir-blas: [0.1.0, 0.0.4, 0.0.2, 0.0.1, ~master]
Search for versions of cblas (1 package suppliers)
Return for cblas: [2.0.1, 2.0.0, 1.0.0, 0.2.0, 0.1.0, 0.0.4, 0.0.3, 0.0.2, 0.0.1, 0.0.0, ~master, ~remove-unittest, ~link-1, ~link, ~John-Colvin-patch-1]
Package mir-lapack contains invalid dependency lapack77 (no version candidates) (ci=10)
- last line repeated infinitly

What ca I do? (Ubuntu 17.10. 64 Bit)

**Comment by 9il** [comment]
lapack77 was a temporary package. Currently it is lapack package. Removing dub.selections.json,  local and global dub caches should solve the problem. If not, please provide full example

**Comment by EmTee70** [comment]
Ok. I removed dub.selection.json and called dub clean and dub clean-caches, was this sufficient?
Probably not. Problem still there:

I took the dub.sdl from the example
and placed the example in source/app.d

dub.sdl:
name "lub"
dependency "lubeck" version="~>0.0"
dependency "mir" version="~>0.7"
libs "lapack" "blas"

**Comment by 9il** [comment]
Please try to remove dub.selections.json and replace dub.sdl with
```
name "lub"
dependency "lubeck" version="~>0.0.4"
libs "openblas"
```
